name: Docs CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Codespell
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: |
          codespell \
            --ignore-words .codespellignore \
            --skip "*.min.js,*.svg,*.png,*.jpg,*.jpeg,*.gif,.git,dist,node_modules" \
            .

      # Markdownlint
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install markdownlint-cli
        run: npm i -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint "**/*.md" -c .markdownlint.json

      # Lychee link checker (internal & external with tuned config)
      - name: Link check (lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .github/lychee/lychee.toml .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}