name: Link Check
on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --exclude-all-private --verbose .
