name: Spell Check
on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: codespell-project/actions-codespell@v2
        with:
          check_hidden: true
          skip: .git,./.github,**/*.pdf,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.zip
          check_filenames: true
          ignore_words_file: .codespellignorewords.txt
