name: Spell Check
on:
  pull_request:
  push: { branches: [ main ] }
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          check_hidden: true
          skip: .git,./.github,./docs/Constella_Decision_Summary_Slide_v1.5.4.pdf
